--- #YAML:1.0
name:                   Bundle-WWW-Scraper-ISBN-Drivers
version:                1.00
abstract:               a Bundle for WWW::Scraper::ISBN drivers.
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  Test::More:                   0.45
recommends:
  Test::More:                   0.70
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
  Test::CPAN::Meta:             0.13
  Test::JSON::Meta:             0.08
build_requires:
  Test::More:                   0.45

provides:
  Bundle::WWW::Scraper::ISBN::Drivers:
    file:     lib/Bundle/WWW/Scraper/ISBN/Drivers.pm
    version:  1.00
no_index:
  directory:
    - t

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
