--- #YAML:1.0
name:                   Bundle-WWW-Scraper-ISBN-Drivers
version:                1.07
abstract:               a Bundle for WWW::Scraper::ISBN drivers.
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                       5.006
recommends:
  Test::CPAN::Meta:           0
  Test::CPAN::Meta::JSON:     0
  Test::Pod:                  1.00
  Test::Pod::Coverage:        0.08
build_requires:
  IO::File:                   0
  Test::More:                 0.70

provides:
  Bundle::WWW::Scraper::ISBN::Drivers:
    file:     lib/Bundle/WWW/Scraper/ISBN/Drivers.pm
    version:  1.07
no_index:
  directory:
    - t

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
